# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
    ]
