# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161203_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='duedate',
            field=models.DateField(default=datetime.datetime(2016, 12, 3, 15, 22, 8, 215413, tzinfo=utc), verbose_name='Data Finalização'),
            preserve_default=False,
        ),
    ]
