# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_problem_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento'),
        ),
        migrations.AddField(
            model_name='problem',
            name='budget_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gasto'),
        ),
    ]
