# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161203_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Orçamento'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='budget_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gasto'),
        ),
    ]
