# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161203_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='contributors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Colaboradores'),
        ),
    ]
