# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161203_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário'),
        ),
    ]
