# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20161203_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gasto'),
        ),
    ]
